// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgB8DVDc8N0IRh-ipCk00c6LkM7fcmlA',
    appId: '1:1051582931156:web:b2e65b6daaa116915f1b41',
    messagingSenderId: '1051582931156',
    projectId: 'loseandfound-project-4e7d8',
    authDomain: 'loseandfound-project-4e7d8.firebaseapp.com',
    storageBucket: 'loseandfound-project-4e7d8.firebasestorage.app',
    measurementId: 'G-620QK0HWR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRowz7dA5wDW7N00pMoYOdQx6lyLyO7LQ',
    appId: '1:1051582931156:android:e215e15b2fb179785f1b41',
    messagingSenderId: '1051582931156',
    projectId: 'loseandfound-project-4e7d8',
    storageBucket: 'loseandfound-project-4e7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEwMpWZpIQp1NydDnXkUJp2L64iD0Y14',
    appId: '1:1051582931156:ios:8570b864375380105f1b41',
    messagingSenderId: '1051582931156',
    projectId: 'loseandfound-project-4e7d8',
    storageBucket: 'loseandfound-project-4e7d8.firebasestorage.app',
    iosBundleId: 'com.example.loseFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEwMpWZpIQp1NydDnXkUJp2L64iD0Y14',
    appId: '1:1051582931156:ios:8570b864375380105f1b41',
    messagingSenderId: '1051582931156',
    projectId: 'loseandfound-project-4e7d8',
    storageBucket: 'loseandfound-project-4e7d8.firebasestorage.app',
    iosBundleId: 'com.example.loseFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgB8DVDc8N0IRh-ipCk00c6LkM7fcmlA',
    appId: '1:1051582931156:web:35d958eb80290b885f1b41',
    messagingSenderId: '1051582931156',
    projectId: 'loseandfound-project-4e7d8',
    authDomain: 'loseandfound-project-4e7d8.firebaseapp.com',
    storageBucket: 'loseandfound-project-4e7d8.firebasestorage.app',
    measurementId: 'G-0P4N0319Q2',
  );
}
